### ISSUE TITLE
Not working for bibleserver.com

### ISSUE THREAD

**Issue by illu3001** [AlexBocken/bibel#1]
The Crawler isn’t working for bibleserver.com. Here is the error message:

```
thread 'main' panicked at src/main.rs:211:51:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by AlexBocken** [comment]
Thanks for the report but I believe you have the wrong repo here. This project provides a German bible for the terminal. (Using AWK and the POSIX shell). It does not have any crawling capabilities nor does it use rust anywere.
